# Generated by Django 5.1.2 on 2024-11-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
